### ISSUE TITLE
新機能についての提案

### ISSUE THREAD

**Issue by kurogee** [kurogee/hitokuchi.github.io#10]
新機能として今「hitokuchi note」と言うものを考えています
概要
・みんなの身の回りにある色々な便利情報を一言でまとめる
　→「こういうバグが起こったら〇〇〇〇すれば良いよ」「この施設はこうだったよ」等
・付箋のような感覚で使える
・URLを任意で貼れる
まだ構想段階なので、意見がほしいです。

**Comment by eimax9668** [comment]
良いと思います

**Comment by kurogee** [comment]
@eimax9668 
「hitokuchi note」を追加しました
「kuroge's branch」内の「note」フォルダを確認して下さい
良ければ「beta」ブランチに入れさせていただきます

**Comment by eimax9668** [comment]
確認しました
良いと思います

**Comment by kurogee** [comment]
@eimax9668 
beta版に追加完了
9月3日(明日)にbeta版をpull requestする予定です
