### ISSUE TITLE
今後の更新内容について

### ISSUE THREAD

**Issue by kurogee** [kurogee/hitokuchi.github.io#12]
更新内容は主に2つあります
1. IPアドレスの収集
2. 上の事に伴った利用規約の作成

です
IPアドレスについては保存期間を定めて保管します
保管する理由は誹謗中傷対策です
利用規約作成についてはIPアドレス収集が出来なくても作ろうと思っています
適切に使ってほしいので

なので意見を募集します
利用規約はこういう項目を追加すれば良い。とか
IPアドレスはこういう感じにすると良い。とか
ぜひ意見を下さい

**Comment by eimax9668** [comment]
良いと思います

利用規約はなかなか見てくれないかもなので
最初は簡単な文章にするのがいいと思います(かんたん利用規約的な)

メッセージ送信のページなどに利用規約のリンクを追加するのが良さそうです

**Comment by kurogee** [comment]
利用規約(的なもの)はbetaブランチの「tos」フォルダーにあります

あとIPアドレスを保管する期間はどうすれば良いと思いますか？
考えているのが1ヶ月、3ヶ月、6ヶ月、1年あたりなんですけど

**Comment by kurogee** [comment]
Pull Request済み
