### ISSUE TITLE
BETA版の編集許可

### ISSUE THREAD

**Issue by kurogee** [kurogee/hitokuchi.github.io#33]
BETA版の編集を許可するので、
・余計な</div>(閉じタグ)がないか
・インデントの数はあっているか
・その他余計なコード、不必要なコードがないか
確認してください

良ければ明日(2023/10/18)の夜に公開するのでこのコメント欄に反応してください

**Comment by eimax9668** [comment]
OK

**Comment by kurogee** [comment]
beta版本公開が決定したのでClose
