### ISSUE TITLE
スマホでのtwo_boxの見え方について

### ISSUE THREAD

**Issue by eimax9668** [kurogee/hitokuchi.github.io#4]
今indexには拡散についてのコンテンツと、お問い合わせフォームが2つ並んで表示されていますが、
スマホ対応のことを考えると、表示が崩れてしまう(?)のでこの2つは分けて表示したほうがいいと思います。
![IMG_9633](https://github.com/kurogee/hitokuchi.github.io/assets/128266762/a4bc3c5e-2396-4c62-b62a-c4e6f4ac6dea)

**Comment by kurogee** [comment]
修正CSSをbetaの方に上げておきますね

**Comment by kurogee** [comment]
多分修正できました
「beta」ブランチから確認できます
