### ISSUE TITLE
hitokuchiで今後作りたいものについて

### ISSUE THREAD

**Issue by kurogee** [kurogee/hitokuchi.github.io#50]
私は今後、hitokuchiで掲示板のようなものを作ろうと計画しています
具体的には
・コメントを投稿できる
・そのコメントに返信できる
・個々のスレッドを見て投稿できる
のようなことを目指しています
まだまだ先の話になるのと、これだと圧倒的に人員が足りなくなるかもしれません
意見を聞かせてほしいです

**Comment by eimax9668** [comment]
> 個々のスレッドを見て投稿できる

スレッドを作れるようにすると管理が大変だと思うから用意されたスレッドにコメントする形がいいかもしれません

**Comment by eimax9668** [comment]
> 圧倒的に人員が足りなくなるかもしれません

開発者を募集したりしますか？

**Comment by kurogee** [comment]
そうですね、信頼できる開発者がほしいです

**Comment by eimax9668** [comment]
掲示板での書き込みは、ログイン必須と匿名どっちがいいでしょうか？

## ログイン必須

- 書き込み者の責任を明確にできる。
- 書き込みの質を向上させることができる。
- 荒らしや誹謗中傷を防ぐことができる
！  書き込みのハードルが高くなる。
！   匿名性がなく、書き込みに消極的になるユーザーがいる。


## 匿名


 -   書き込みのハードルが低くなる。
  -  書き込みに消極的になるユーザーが減る。
 -   本音を言いやすい雰囲気になる。
 ！ 書き込み者の責任を明確にできない。
 ！  書き込みの質が低下する可能性がある。
 ！  荒らしや誹謗中傷が起こりやすい。

**Comment by kurogee** [comment]
IPアドレスをちゃんと収集してますよってことを言いつつな匿名制にしたいと考えています

**Comment by eimax9668** [comment]
名前...どうしますか？

普通に「ひとくち掲示板」でもいい感じな気がします🤔

**Comment by eimax9668** [comment]
OK

**Comment by eimax9668** [comment]
> 日本語のindexのmailやreviewと同じ列に掲示板へのメニューを追加

Pull request 済み

**Comment by kurogee** [comment]
掲示板完成に伴いここの話し合いの場所をクローズします
