### ISSUE TITLE
認証者制度について

### ISSUE THREAD

**Issue by kurogee** [kurogee/hitokuchi.github.io#6]
今「kuroge's branch」に認証者アイコンとデベロッパーアイコンとそれを制御するプログラムを追加しました
認証者については今後よく使ってくれる他のユーザが出来た時に付与するものとします
デベロッパーアイコンはここGithubにて開発をしてくださる方に付与します
以上の案が良ければ「beta」ブランチに追加しようと考えています

またhitokuchiの宣伝方法についても検討中です
google analyticsを活用したりSNSの活用も視野に入れております

ご意見をお待ちしています

**Comment by kurogee** [comment]
@eimax9668 
この2つの事について意見をください
後今日か明日あたりにbetaをまとめようと思っています

**Comment by eimax9668** [comment]
認証者制度について - 
良いと思います


 

宣伝について - 
> SNSの活用も視野に入れております

良いと思います
Twitterでの宣伝が効果的だと思います

**Comment by eimax9668** [comment]
すいません...「更新したデータ」について説明して欲しいです 

Betaブランチに Ei max's branch をpull request すればいいということですか？

今、Github勉強中で...   ごめんなさい🙇‍♂️

**Comment by kurogee** [comment]
> Betaブランチに Ei max's branch をpull request すればいいということですか？

そういう事です。
