### ISSUE TITLE
Forumで画像をアップできるようにしたい

### ISSUE THREAD

**Issue by eimax9668** [kurogee/hitokuchi.github.io#65]
**「Forumで画像をアップできるようにして」**　と言われました
意見をください

**Comment by kurogee** [comment]
画像は容量などが大きく、またサーバーなども無いためアップロードは難しいですね...
ただ外部アップローダーでアップロードした画像のURLで画像を表示するのは出来そうですね

**Comment by kurogee** [comment]
alphaに画像URLを画像として貼れるように機能を追加しておきました
